### ISSUE TITLE
Weapon + item wheel

### ISSUE THREAD

**Issue by GhzGarage** [qbcore-redm-framework/qbr-core#23]
- Holding tab still opens the weapon wheel
- Holding F4 still opens the items wheel

**Comment by Demo4889** [comment]
I know it's not a great way to do it... but...

`CreateThread(function()
    while true do
        Wait(0)
        if isLoggedIn then
            DisableControlAction(0, 0x580C4473, true) -- Left Alt (INPUT_HUD_SPECIAL)
            DisableControlAction(0, 0xCF8A4ECA, true) -- Left Alt (INPUT_REVEAL_HUD)
            DisableControlAction(0, 0x1F6D95E5, true) -- F4 (INPUT_SELECT_ITEM_WHEEL)
        end
    end
end)`

Figured I'd just throw this in there, unless you guys can find another way to do it that's better

**Comment by DosKit** [comment]
I went ahead and did a pull request to disable the Weapon Wheel and Item Wheel inside the inventory as it already had a thread disabling similar things - https://github.com/qbcore-redm-framework/qbr-inventory/pull/29
