### ISSUE TITLE
When the player is dead, shooting the player's head will knock the player's head off

### ISSUE THREAD

**Issue by HuyaSL666** [qbcore-redm-framework/qbr-core#51]
When the player is killed by a weapon and then shoots the player's head again before performing an action, the player's head can be knocked out. When the player is resurrected, the head is gone. This problem should be fixed as soon as possible.

**Comment by HuyaSL666** [comment]
![image](https://github.com/qbcore-redm-framework/qbr-core/assets/103110822/fb95b4cb-24a1-445f-bb82-7c593aa48a53)

**Comment by KetsMiku** [comment]
Me too, but I don't know how to fix it

**Comment by DosKit** [comment]
We will look into this.

**Comment by DosKit** [comment]
If you haven't figured this out here is a way to remove. I will get make a PR for this in the next few days. The Head Will still Blow off for a split second but should instantly reappear.

SetPedConfigFlag(PlayerPedId(), 305, true) -- Disable Head Gore
