### ISSUE TITLE
exports['qbr-core']:AddItem

### ISSUE THREAD

**Issue by draobrehtom** [qbcore-redm-framework/qbr-core#56]
Hello, 

There can be a possible obstacle for defining new inventory items via exports. Please, take a look on code example I've used:
```lua
local framework = 'qbr-core'
local itemName = 'beartrap'

-- Define new item
exports[framework]:AddItem(itemName, {
    ['name'] = itemName,        
    ['label'] = 'Beartrap',    
    ['weight'] = 20000, 
    ['type'] = 'item', 
    ['image'] = 'beartrap.png',        
    ['unique'] = false, 
    ['useable'] = true,  
    ['shouldClose'] = true, 
    ['combinable'] = nil, 
    ['level'] = 0, 
    ['description'] = 'Beartrap', 
    ["created"] = nil, 
    ["decay"] = 1.0, 
    ["delete"] = true,
})

```
Provided code sample causing next output in server console:

![image](https://github.com/qbcore-redm-framework/qbr-core/assets/6503721/568cc339-cb3f-4b16-a544-1b87ab1eeec9)

By a quick look, the issue is located under 
https://github.com/qbcore-redm-framework/qbr-core/blob/2adddda265623000a97a14a84cf34f61d7b15baf/server/exports.lua#L52

From my perspective it looks like the issue is lying in undefined **QRCore.Shared.Items** variable, which seems is a legacy code and could be replaced by **exports['qbr-core']:GetItems()**. 

May be useful info:
- I've used a fresh installation of framework via txAdmin recipe

Thanks, appreciate your work!

**Comment by DosKit** [comment]
PR has been Submitted to Correct this issue. Once these get pulled this should correct the issue. If you wanna see the changes they are here.

https://github.com/qbcore-redm-framework/qbr-core/pull/57/commits/f4fbdd0893f23e40e7b2d9fe4768f57d69ed8bd1
